# -*- coding: utf-8 -*-
"""rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yk3rU1mjsGoi100KSE-XDWG29aZk808_
"""

import os
import re
import chromadb

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_groq import ChatGroq

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

llm = ChatGroq(
    groq_api_key=os.getenv("GROQ_API_KEY"),
    model_name="llama-3.3-70b-versatile",
    temperature=0
)

retriever = None


def clean_text(text):
    text = re.sub(r"-\n", "", text)
    text = re.sub(r"\n", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def process_pdf(file):

    global retriever

    loader = PyPDFLoader(file.name)
    docs = loader.load()

    for doc in docs:
        doc.page_content = clean_text(doc.page_content)

    chunks = splitter.split_documents(docs)

    client = chromadb.Client()

    vectorstore = Chroma(
        client=client,
        collection_name="pdf_chat",
        embedding_function=embeddings,
    )

    vectorstore.add_documents(chunks)

    retriever = vectorstore.as_retriever(
        search_kwargs={"k":3}
    )

    return "✅ PDF uploaded successfully."


def chat(question):

    global retriever

    if retriever is None:
        return "Please upload a PDF first."

    docs = retriever.invoke(question)

    context = "\n\n".join(
        doc.page_content for doc in docs
    )

    prompt = f"""
Use ONLY the provided context.

Context:
{context}

Question:
{question}

Answer:
"""

    response = llm.invoke(prompt)

    return response.content